# Generated by Django 4.1.2 on 2024-06-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='avisos',
            new_name='aviso',
        ),
    ]
