# Generated by Django 4.1.2 on 2024-07-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_rename_avisos_contacto_aviso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='url_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
